'\" t
.\"     Title: btrfs-map-logical
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/05/2021
.\"    Manual: Btrfs Manual
.\"    Source: Btrfs v5.10.1
.\"  Language: English
.\"
.TH "BTRFS\-MAP\-LOGICAL" "8" "02/05/2021" "Btrfs v5\&.10\&.1" "Btrfs Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
btrfs-map-logical \- map btrfs logical extent to physical extent
.SH "SYNOPSIS"
.sp
\fBbtrfs\-map\-logical\fR \fI<options>\fR \fI<device>\fR
.SH "DESCRIPTION"
.sp
\fBbtrfs\-map\-logical\fR can be used to find out what the physical offsets are on the mirrors, the result is dumped to stdout by default\&.
.sp
Mainly used for debug purpose\&.
.SH "OPTIONS"
.PP
\-l|\-\-logical \fI<logical_num>\fR
.RS 4
Logical extent to map\&.
.RE
.PP
\-c|\-\-copy \fI<copy>\fR
.RS 4
Copy of the extent to read(usually 1 or 2)\&.
.RE
.PP
\-o|\-\-output \fI<filename>\fR
.RS 4
Output file to hold the extent\&.
.RE
.PP
\-b|\-\-bytes \fI<bytes>\fR
.RS 4
Number of bytes to read\&.
.RE
.SH "EXIT STATUS"
.sp
\fBbtrfs\-map\-logical\fR will return 0 if no error happened\&. If any problems happened, 1 will be returned\&.
.SH "SEE ALSO"
.sp
\fBmkfs\&.btrfs\fR(8)
